export const PathConstants = {
  LOGIN_PATH: 'login',
  HOME_PATH: '',
  REGISTER_PATH: 'register',
  FORGOT_PASSWORD_PATH: 'forgot-password',
  MANAGE_USERS_PATH: 'manage-users',
  DOCTORS_PATH: 'doctors',
  DOCTOR_DETAILS_PATH: 'doctors/:email',
  MANAGE_APPOINTMENTS_PATH: 'manage-appointments/:id',
  MY_APPOINTMENTS_PATH: 'my-appointments',
  MANAGE_SPECIALTIES_PATH: 'manage-specialties',
  MANAGE_DOCTORS_PATH: 'manage-doctors',
  MANAGE_SCHEDULES_PATH: 'manage-schedules',
  MANAGE_PATIENTS_PATH: 'manage-patients',
  MANAGE_ROLES_PATH: 'manage-roles',
  MANAGE_BITACORA_PATH: 'bitacora',
};
