export const UserFormValidationConstants = {
  MIN_NAME_LENGTH: 1,
  MAX_NAME_LENGTH: 30,
  MIN_SURNAME_LENGTH: 1,
  MAX_SURNAME_LENGTH: 30,
  MIN_PHONE_NUMBER_LENGTH: 8,
  MAX_PHONE_NUMBER_LENGTH: 15,
  PESEL_LENGTH: 6 | 7 | 8 | 9 | 10,
  MIN_PESEL_LENGTH: 6,
  MAX_PESEL_LENGTH: 10,
  MIN_PASSWORD_LENGTH: 8,
  MAX_PASSWORD_LENGTH: 100,
};
